version: "3"
services:
  redis:
    extends:
      file: ../trade-remedies-api/docker-compose.yml
      service: redis
    networks:
      - proxynet
  postgres:
    extends:
      file: ../trade-remedies-api/docker-compose.yml
      service: postgres
    networks:
      - proxynet
  elasticsearch:
    extends:
      file: ../trade-remedies-api/docker-compose.yml
      service: elasticsearch
    networks:
      - proxynet
  api:
    extends:
      file: ../trade-remedies-api/docker-compose.yml
      service: api
    depends_on:
      - postgres
      - redis
    networks:
      - proxynet
  public:
    extends:
      file: ../trade-remedies-public/docker-compose.yml
      service: public
    depends_on:
      - redis
    networks:
      - proxynet
  caseworker:
    extends:
      file: ../trade-remedies-caseworker/docker-compose.yml
      service: caseworker
    depends_on:
      - redis
    networks:
      - proxynet
networks:
  proxynet:
    name: trade_remedies_network
volumes:
  postgres_data:
    driver: local
