version: "3"

services:
  postgres:
    image: postgres:10.1
    restart: unless-stopped
    volumes:
     - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trade_remedies
      POSTGRES_USER: uktrade
      POSTGRES_PASSWORD: uktrade
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  # minio-s3:
  #   build: ./minio
  #   volumes:
  #    - ./test-data:/test-data
  #   ports:
  #     - "9000:9000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    network_mode: host

  trade-remedies-api:
    container_name: tr-api
    build: ../trade-remedies-api
    restart: unless-stopped
    network_mode: host
    environment:
      DB_HOST: localhost
      DB_USER: uktrade
      DB_PASSWORD: uktrade
      DB_NAME: trade_remedies
      DB_PORT: 5432
      DJANGO_SECRET_KEY: changeme
      DEBUG: "True"
    env_file:
      - ../trade-remedies-api/local.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ../trade-remedies-api:/opt/traderemedies/api
    entrypoint: dockerize -timeout 120s -wait tcp://localhost:6379 -wait tcp://localhost:5432 /opt/traderemedies/api/bootstrap.sh web

  trade-remedies-caseworker:
    container_name: tr-case
    build: ../trade-remedies-caseworker
    restart: unless-stopped
    network_mode: host
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - ../trade-remedies-caseworker/local.env
    # environment:
    #   DEBUG: "True"
    #   DJANGO_SECRET_KEY: "changeme"
    #   REDIS_DATABASE_NUMBER: "1"
    #   CELERY_REDIS_DATABASE_NUMBER: "1"
    #   VCAP_SERVICES: "{\"redis\":[{\"credentials\":{\"uri\":\"redis://localhost:6379\"}}]}"
    #   API_BASE_URL: "http://localhost:8000"
    #   ENVIRONMENT_KEY: CW-ENV
    tty: true
    volumes:
      - ../trade-remedies-caseworker:/opt/traderemedies/caseworker

  trade-remedies-public:
    container_name: tr-pub
    build: ../trade-remedies-public
    restart: unless-stopped
    network_mode: host
    ports:
      - "8002:8002"
    depends_on:
      - redis
    env_file:
      - ../trade-remedies-public/local.env
    #environment:
    #  HEALTH_CHECK_TOKEN: "42d307b99372c95a28dd029339053e7dfff6982b"
    #   DEBUG: "True"
    #   DJANGO_SECRET_KEY: "changeme"
    #   REDIS_DATABASE_NUMBER: "2"
    #   CELERY_REDIS_DATABASE_NUMBER: "2"
    #   VCAP_SERVICES: "{\"redis\":[{\"credentials\":{\"uri\":\"redis://localhost:6379\"}}]}"
    #   API_BASE_URL: "http://localhost:8000"
    #   ENVIRONMENT_KEY: PUB-ENV
    tty: true
    volumes:
      - ../trade-remedies-public:/opt/traderemedies/public

  elastic-search:
    image: elasticsearch:6.8.7
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
