version: "3"

services:
  postgres:
    image: postgres:10.1
    restart: unless-stopped
    volumes:
     - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trade_remedies
      POSTGRES_USER: uktrade
      POSTGRES_PASSWORD: uktrade
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  
  elastic-search:
    image: elasticsearch:6.8.7
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
