version: "3"
volumes:
  postgres_data:
    driver: local
services:
  redis:
    extends:
      file: ../trade-remedies-api/docker-compose.yml
      service: redis
    networks:
      - proxynet
  postgres:
    extends:
      file: ../trade-remedies-api/docker-compose.yml
      service: postgres
    networks:
      - proxynet
  elasticsearch:
    extends:
      file: ../trade-remedies-api/docker-compose.yml
      service: elasticsearch
    networks:
      - proxynet
  api:
    extends:
      file: ../trade-remedies-api/docker-compose.yml
      service: api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - proxynet
  apitest:
    extends:
      file: ../trade-remedies-api/docker-compose.yml
      service: apitest
    depends_on:
      - postgres
      - redis
    networks:
      - proxynet
  public:
    extends:
      file: ../trade-remedies-public/docker-compose.yml
      service: public
    depends_on:
      - redis
    networks:
      - proxynet
  caseworker:
    extends:
      file: ../trade-remedies-caseworker/docker-compose.yml
      service: caseworker
    depends_on:
      - redis
    networks:
      - proxynet
  selenium-hub:
    image: selenium/hub:3.141.59-vanadium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    depends_on:
      - public
      - caseworker
    networks:
      - proxynet
  chrome:
    image: selenium/node-chrome-debug:3.141.59-vanadium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    networks:
      - proxynet
networks:
  proxynet:
    name: trade_remedies_network
